### ISSUE TITLE
Is this built with Helix?

### ISSUE THREAD

**Issue by ylluminarious** [wasmerio/ruby-ext-wasm#3]
### Summary

I see that a lot of the code for this project is written in Rust. I'm just curious if you've written this as a C extension, [with Rust instead of C via Helix.](https://usehelix.com/) I'm also curious if it is thus bound to MRI only or if it can run on other Ruby implementations, such as the up-and-coming speed demon TruffleRuby.

**Comment by aergonaut** [comment]
The `Cargo.toml` [lists rutie as a dependency](https://github.com/wasmerio/ruby-ext-wasm/blob/master/Cargo.toml#L20), rather than Helix.

I believe this does mean this gem will only work with MRI, as rutie also binds to the MRI C libraries.

**Comment by ylluminarious** [comment]
@aergonaut Ah, I see, thanks for the info. For future reference, [Rutie is located here.](https://github.com/danielpclark/rutie)

**Comment by Hywan** [comment]
Yeah, I decided to go with Rutie since it seems to be more maintained than Helix.
