### ISSUE TITLE
Export Wasm globals ?

### ISSUE THREAD

**Issue by ljulliar** [wasmerio/ruby-ext-wasm#30]
Hi there,

It is unclear to me whether one can access exported Wasm globals with ruby-ext-wasm. I tried  and I got some kind of weird errors when instatiating a wasm module with exported globals like "global must be a const" (although the wasm code was perfectly valid)
Thanks!

**Comment by Hywan** [comment]
I can implement that quickly, as I did for `python-ext-wasm` in https://github.com/wasmerio/python-ext-wasm/pull/120. Would it fit your needs?

**Comment by ljulliar** [comment]
That would be great! In the meantime I put a workaround in place but not
very elegant (basically I export a function that returns the value of the
global).

Side question too: is there a way from the Ruby extension to **import** a
function in the wasm module that you can then call from the wasm code ?

Thanks!

Laurent

**Comment by Hywan** [comment]
See #32 for the Global API.

To answzer your side question: For the moment, no, we need to support polymorphic host functions in Wasmer (the Wasmer runtime) directly. I'm working on it, since it will unblock host functions support in Ruby.

**Comment by ljulliar** [comment]
Hi Ivan,

Are you thinking of releasing the wasmer rubygem 0.3.1 with this new
feature for globals or there is just no need for it ?

Thanks!
